## Creating array from scratch

In [1]:
import numpy as np
zeroes=np.zeros((3,4))
print("Zeroes array: \n",zeroes)

Zeroes array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [2]:
ones=np.ones((2,3))
print("ones array: \n",ones)

ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [3]:
full=np.full((3,4),8)
print("FULL array: \n",full)

FULL array: 
 [[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [5]:
random=np.random.random((4,5))
print(random)

[[0.87832491 0.13230879 0.51431641 0.79314097 0.4026371 ]
 [0.19381903 0.37664824 0.8778471  0.22986688 0.14157484]
 [0.95640553 0.76236434 0.79798177 0.48875121 0.1445048 ]
 [0.17578196 0.28891594 0.66436508 0.64903604 0.1131871 ]]


In [4]:
import numpy as np
sequence=np.arange(0,10,2)
print(sequence)

[0 2 4 6 8]
