## Operations on Numpy Array

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Basic slicing: ",arr[2:7])
print("Basic slicing with step: ",arr[2:8:3])

Basic slicing:  [3 4 5 6 7]
Basic slicing with step:  [3 6]


In [7]:
array_2d=np.array([[1,2,3],
                   [4,5,6],
                   [10,11,12]])
print("Specific element: ",array_2d[1,2])
print("entire row: ",array_2d[1])
print("entire column: ",array_2d[:,2])


Specific element:  6
entire row:  [4 5 6]
entire column:  [ 3  6 12]


## Sorting numpy arrays

In [12]:
unsorted=np.array([8,5,4,9,3,2,2,7,1,6])
print(np.sort(unsorted))
array_2d_unsorted=np.array([[3,1],[1,2],[2,3]])
print("sorted 2d array by column: ",np.sort(array_2d_unsorted,axis=0))
print("sorted 2d array by column: ",np.sort(array_2d_unsorted,axis=1))

[1 2 2 3 4 5 6 7 8 9]
sorted 2d array by column:  [[1 1]
 [2 2]
 [3 3]]
sorted 2d array by column:  [[1 3]
 [1 2]
 [2 3]]


## Filters

In [13]:
natural_numbers=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
even_numbers=natural_numbers[natural_numbers%2==0]
print(even_numbers)

[ 2  4  6  8 10 12 14 16]


## Filter with mask

In [14]:
mask=natural_numbers>5
print(natural_numbers[mask])

[ 6  7  8  9 10 11 12 13 14 15 16]


## fancy indexing vs np.where()

In [15]:
indices=[0,2,4,5]
print(natural_numbers[indices])

[1 3 5 6]


In [17]:
np_where_result=np.where(natural_numbers>5)
print(natural_numbers[np_where_result])

[ 6  7  8  9 10 11 12 13 14 15 16]


In [19]:
condition_array=np.where(natural_numbers>5)
print(condition_array)
print(natural_numbers[condition_array])

(array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),)
[ 6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
condition_array=np.where(natural_numbers>5,True,False) #just like if and else
print(condition_array)
print(natural_numbers[condition_array])

[False False False False False  True  True  True  True  True  True  True
  True  True  True  True]
[ 6  7  8  9 10 11 12 13 14 15 16]


## Adding and removing data


In [22]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined_array=arr1+arr2  # this will add the two arrays
actually_combined_array=np.concatenate((arr1,arr2))
print(combined_array) 
print(actually_combined_array)

[5 7 9]
[1 2 3 4 5 6]


## array compatibility

In [27]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,5,9])
print("compatibility shapes of array: ",a.shape==b.shape)
print("compatibility shapes of array: ",a.shape==c.shape)
print("compatibility shapes of array: ",b.shape==c.shape)

compatibility shapes of array:  True
compatibility shapes of array:  False
compatibility shapes of array:  False


## adding rows and columns

In [34]:
original=np.array([[5,4,8],[1,2,3]])
new_row=np.array([9,8,7])
orig_with_new_row=np.vstack((original,new_row))
print(original)
print(orig_with_new_row)
new_col=np.array([[10],[10]])
# new_col_2=np.array([[10],[10],[10]])
orig_with_new_col=np.hstack((original,new_col))
# orig_with_new_col_2=np.hstack((orig_with_new_row,new_col))
print(orig_with_new_col)
# print(orig_with_new_col_2)

[[5 4 8]
 [1 2 3]]
[[5 4 8]
 [1 2 3]
 [9 8 7]]
[[ 5  4  8 10]
 [ 1  2  3 10]]


## deletion

In [35]:
my_arr=np.array([1,2,3,4,5,6])
deleted=np.delete(my_arr,2)
print(deleted)

[1 2 4 5 6]
