## vectors , matrix , Tensor

In [1]:
import numpy as np
vector=np.array([1,2,5,4,8,9,7,6])
print(vector)

[1 2 5 4 8 9 7 6]


In [4]:
matrix=np.array([[1,2,5,4,6],[8,5,4,1,2]])
print(matrix)

[[1 2 5 4 6]
 [8 5 4 1 2]]


## Array Properties


In [9]:
array=np.array([[1,2,3],[5,8,7]])
print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

2
(2, 3)
6
int64


## array reshaping

In [19]:
arr=np.arange(12)
print("original array : ",arr)
reshaped=arr.reshape(6,2)
print("\nreshaped array : ",reshaped)
flattened=reshaped.flatten()
print("Flattened : ",flattened)
# ravel returns view (original , but not the copy)
ravelled=reshaped.ravel()
print("ravelled : ",ravelled)
#Transpose
transposed=reshaped.T
print("transposed array: ",transposed)

original array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshaped array :  [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
Flattened :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravelled :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed array:  [[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [7]:
tensor=np.array([[[1,2],[3,4],[8,9]],[[9,8],[3,4],[7,4]],[[1,2],[3,4],[8,9]],[[9,8],[3,4],[7,4]]])
print(tensor)

[[[1 2]
  [3 4]
  [8 9]]

 [[9 8]
  [3 4]
  [7 4]]

 [[1 2]
  [3 4]
  [8 9]]

 [[9 8]
  [3 4]
  [7 4]]]
